server:
  port: 8082

spring:
  application:
    name: survey-service

  datasource:
    url: jdbc:mysql://172.16.212.107:3306/surveyDB?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: formvey1234!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.212.105:8761/eureka

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

cloud:
  aws:
    s3:
      bucket: eraofband
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true
      access-key: AKIARNTNV6CZZBBIWQMR
      secret-key: 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
