server:
  port: 8000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://172.16.212.104, http://172.16.212.104:3000, http://localhost:3000, http://127.0.0.1:3000"
            allow-credentials: true
            allowedHeaders: "*"
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: member-service
          uri: http://172.16.212.106:8081
          predicates:
            - Path=/member-service/**
        - id: survey-service
          uri: http://172.16.212.107:8082
          predicates:
            - Path=/survey-service/**
        - id: response-service
          uri: http://172.16.212.108:8083
          predicates:
            - Path=/response-service/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://172.16.212.105:8761/eureka